version: '3.8'

services:
  jupiter-gpu-torch-tf:
    build:
      context: .
      dockerfile: jupyter-dockerfiles/Dockerfile-cpu
    image: jupiter-cpu
    container_name: jupiterlab
    ports:
      - "8789:8789"
    volumes:
      - ./:/playground
